apiVersion: apps/v1
kind: Deployment
metadata:
  name: apcups-exporter
  namespace: apcups
  labels:
    app.kubernetes.io/name: apcups-exporter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: apcups-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apcups-exporter
    spec:
      containers:
        - name: apcups-prometheus-exporter
          image: ghcr.io/mamercad/apcups-prometheus-exporter:devel
          imagePullPolicy: Always
          env:
            - name: EXPORTER_PORT
              value: "8000"
            - name: POLLING_INTERVAL
              value: "60"
          ports:
            - containerPort: 8000
              name: prom-metrics
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
